source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '12.0'

target 'BetterKeyboardSDK_Example' do
    pod "BetterKeyboardSDK", path: "../"
end

target 'BetterKeyboardSDK_Tests' do
    pod "BetterKeyboardSDK", path: "../"
end
