source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BetterKeyboardSDK_Example', :exclusive => true do
  pod "BetterKeyboardSDK", :path => "../"
end

target 'BetterKeyboardSDK_Tests', :exclusive => true do
  pod "BetterKeyboardSDK", :path => "../"
end
